### ISSUE TITLE
Error should read "Too few input arguments."

### ISSUE THREAD

**Issue by kleinma** [horchler/waittext#1]
Problem found on the following line.
https://github.com/horchler/waittext/blob/7d285c2877085bd57e3a61b727b86b275b8851f8/waittext.m#L101

**Comment by horchler** [comment]
Fixed. Thank you.

**Comment by kleinma** [comment]
`nargoutchk(0,1)` perhaps?
https://github.com/horchler/waittext/blob/bb62a5a23b44cce76eafb9d209f6e845e7e4abef/waittext.m#L101

**Comment by horchler** [comment]
Gah. Sorry. It's fixed for real now.
